### ISSUE TITLE
install extension failed

### ISSUE THREAD

**Issue by geekidentity** [crazy-max/docker-flarum#96]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-flarum/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

when I install extension, sometime have follow error:

### Expected behaviour

install extension success.

### Actual behaviour

![image](https://github.com/crazy-max/docker-flarum/assets/23332528/6589c16d-cab1-4860-83e3-a3e13498fb85)

### Steps to reproduce

docker compose exec flarum extension require itnt/flarum-uitab

Unable to reproduce stably

### Docker info

```text
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.14.1)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 37
  Running: 15
  Paused: 0
  Stopped: 22
 Images: 1008
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.81.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.4GiB
 Name: asus
 Docker Root Dir: /app/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Docker Compose config

```yaml
name: flarum-xxlab
services:
  flarum:
    container_name: flarum-xxlab
    depends_on:
      msmtpd:
        condition: service_started
    environment:
      DB_HOST: 192.168.31.121
      DB_NAME: flarum_xxlab
      DB_PASSWORD: geek1994
      DB_PORT: "3307"
      DB_USER: flarum
      FLARUM_BASE_URL: http://bbs.xxlab.tech
      FLARUM_DEBUG: "false"
      LOG_IP_VAR: remote_addr
      MEMORY_LIMIT: 1024M
      OPCACHE_MEM_SIZE: "128"
      PGID: "1000"
      PUID: "1000"
      REAL_IP_FROM: 0.0.0.0/32
      REAL_IP_HEADER: X-Forwarded-For
      TZ: Europe/Paris
      UPLOAD_MAX_SIZE: 16M
    image: crazymax/flarum:latest
    networks:
      default: null
    ports:
    - target: 8000
      published: "8006"
      protocol: tcp
    restart: always
    volumes:
    - type: bind
      source: /app/flarum-xxlab/data/
      target: /data
      bind:
        create_host_path: true
  msmtpd:
    container_name: flarum_msmtpd-xxlab
    environment:
      SMTP_AUTH: "on"
      SMTP_FROM: xx_lab@163.com
      SMTP_HOST: smtp.163.com
      SMTP_PASSWORD: KIOMKIQNQUHJSFSU
      SMTP_STARTTLS: "on"
      SMTP_TLS: "on"
      SMTP_TLS_CHECKCERT: "on"
      SMTP_USER: xx_lab@163.com
      TZ: Europe/Paris
    image: crazymax/msmtpd:latest
    networks:
      default: null
    restart: always
networks:
  default:
    name: flarum-xxlab_default
```

### Logs

```text
$ docker compose exec flarum extension require itnt/flarum-uitab
./composer.json has been updated
Running composer update itnt/flarum-uitab
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking itnt/flarum-uitab (v0.4.2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading itnt/flarum-uitab (v0.4.2)
    Failed to download itnt/flarum-uitab from dist: The "https://api.github.com/repos/littlegolden/flarum-uitab/zipball/f6f24b394a9ae3e7867ee149c9ea8da7fd04b36f" file could not be downloaded (HTTP/2 404 ):
{"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
    Now trying to download from source

In GitDownloader.php line 82:

  git was not found in your PATH, skipping source download


require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]
```

### Additional info

this is second time i miss this error, i remove all data and reinstall extenion, is ok, but when i install again，it has this error.

I have 2 env, and another never have this error.
